source 'https://rubygems.org'
ruby '2.1.5'

gem 'sinatra'
gem 'sinatra-contrib', github: 'maccman/sinatra-contrib'
gem 'sinatra-sequel', require: 'sinatra/sequel'
gem 'thin'
gem 'i18n'
gem 'activesupport'
gem 'rake'
gem 'builder'
gem 'json'
gem 'bk'
gem 'nestful', github: 'maccman/nestful'
gem 'apihub-contrib', git: 'https://f79ceb3130051b8c05fdb7e510749b2783e06954:x-oauth-basic@github.com/maccman/apihub-contrib.git'
gem 'email_providers', git: 'https://f79ceb3130051b8c05fdb7e510749b2783e06954:x-oauth-basic@github.com/maccman/email_providers.git'
gem 'mail'
gem 'dalli'
gem 'mash', github: 'clearbit/mash'
gem 'sidekiq'
gem 'clearbit'
gem 'redcarpet', '3.1.1'
gem 'pg'

group :development do
  gem 'rerun'
end
